import { Avatar, Box, Button, Center, HStack, Text } from '@chakra-ui/react';
import { Link } from 'react-router-dom';
import {
  CardWithPieChart,
  TotalClientsCard,
  ClientsListCard,
  TerminalsCard,
  MerchantsListCard,
  MoneyInCard,
  CommisionsCard,
} from 'components/cards';
import TransactionHistoryTable from 'components/tables/transactionHistory';
import Chart from 'react-apexcharts';
import { WarningTwoIcon } from '@chakra-ui/icons';
import { terminals, sideAreaChartOptions, volumeOptions, mainChartOptions } from './dashboard.utils';
import ShortUniqueId from 'short-unique-id';
import { formatAmount } from 'utils/utils';
import { Grid, GridItem } from '@chakra-ui/react'


function Dashboard() {

  const uid = new ShortUniqueId({ length: 5 })

  return (
    <Box  sx={{ width: 'calc(100vw - 220px)' }} flexGrow='1'  overflow='hidden' display='flex'>
      {/**Box 1 */}
      <Box h='90vh' flex='2 2 2rem' display='flex' flexDirection='column' gap={4} p={4}>

        <MerchantsListCard paddingBottomx={20}/>
        <ClientsListCard />
      </Box>

      {/**Box 2 */}
      
      <Box display='flex' marginLeft={30} flexDirection='column' gap={4} flex='2 2 2rem' pt={4} >
      <Text fontSize='larger' fontWeight='bold' >Welcome Back!</Text> 
        <Box w='full' bg='uiGray' pt={3} borderRadius='md' shadow='md'>
          <Box display='flex' pl={2} paddingBottom={5} paddingRight={4} gap={2}>
            <HStack>
            <Avatar marginLeft={8} marginRight={70} size='md' src='https://bit.ly/dan-abramov' />
            </HStack>
           <MoneyInCard title='Amount generated for commision' amount={450000} type='commision' />
          </Box>
          {/* <Chart key={uid()} type='area' width='100%' series={mainChartOptions.series} options={mainChartOptions.options} /> */}
          <Box display='flex' pl={2} paddingRight={4} gap={2}>
          <HStack paddingRight={5}>
           <MoneyInCard title='Transactions' amount={1300} type='transaction' />
          </HStack>
          <MoneyInCard title='Amount generated by company' amount={39000} type='company' />
          </Box><br></br>
        </Box>

        
        

        {/** TRANSACTION HISTORY TABLE */}
        <Box w='full'>
          <TransactionHistoryTable fontWeight='bold' caption='Recent Transactions' size='sm' isDashboard={true} />
        </Box>

      </Box>

      {/**Box 3 */}
      <Box display='flex' flexDirection='column' gap={4} alignItems='flex-end' flex='2 2 2rem' pr='20px' pt={4}>

      
        {/** TRANSACTION VOLUME CHART */}
        <Box w='150px' marginRight={20}>
        <CommisionsCard w='50px' total={'1%'} />
        </Box>
        <Box w='400px'>
          <Center><Text fontWeight='bold'>Transaction volume this week</Text></Center>
          <Chart key={uid()} type='bar' width='100%' series={volumeOptions.series} options={volumeOptions.options} />
        </Box>

        {/** NUMBER OF TRANSACTIONS CHART */}
        <Box w='400px'>
        <TerminalsCard data={terminals} />
        </Box>
      </Box>


    </Box >
  );
}

export default Dashboard;
